language: python
python:
  - "2.7"
  - "3.3"

before_install:
  - curl -L https://github.com/coreos/etcd/releases/download/v2.0.10/etcd-v2.0.10-linux-amd64.tar.gz | tar zxv
  - pip install --upgrade setuptools

# command to install dependencies
install: 
  - python bootstrap.py
  - bin/buildout

# command to run tests
script:
  PATH=$PATH:./etcd-v2.0.10-linux-amd64/ bin/test

# Add env var to detect it during build
env: TRAVIS=True
